config/routes.rb
Amfsg::Application.routes.draw do
resources :messages, only: [:new, :create]

  match '/about_us', to: 'static_pages#about_us'
  match '/services', to: 'static_pages#services'
  match '/training', to: 'static_pages#training'
  match '/fees', to: 'static_pages#fees'
  match '/contact_us', to: 'messages#new'

   root :to => 'static_pages#index'

end

app/models/message.rb
class Message
  include ActiveAttr::Model
  
  attribute :name
  attribute :email
  attribute :content
  attribute :subject
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, :if => :email?
  validates_length_of :content, :maximum => 500
  validates_length_of :subject, :maximum => 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message=Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMessage.contact_message(@message).deliver
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      render "new"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about_us
  end

  def services
  end

  def training
  end

  def fees
  end

  def contact_us
  end
  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(current_page)
  base_title = "AMERICAN FINANCIAL SERVICES GROUP"
  if current_page.empty?
    "#{base_title} | A Unique Opportunity to Raise Business Capital"
  else
    "#{base_title} | #{current_page}"
  end
  end


  def homepage?
    params[:action]=="index" && params[:controller]="static_pages" 
  end

  def test?
    params[:action ]=="test" && params[:controller]="static_pages"
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def homepage?
    params[:action]=="index" && params[:controller]="static_pages"
  end
end

app/views/contact_message/contact_message.html.erb
<table>
  <tr>
    <th>Date Sent:</th>
    <td><%= DateTime.now.strftime("%b %d at %I:%M %p") %></td>
  </tr>
  <tr>
    <th>From:</th>
    <td><%= @contact_email.name %></td>
  </tr>
    <tr>
    <th>Subject:</th>
    <td><%= @contact_email.subject %></td>
  </tr>
  <tr>
    <th>Message:</th>
    <td><%= @contact_email.content %>
</td>
  </tr>

</table>

app/views/contact_message/contact_message.text.erb
Date Sent:  <%= DateTime.now.strftime("%b %d at %I:%M %p") %>
From:  <%= @contact_email.name %>
Subject:  <%= @contact_email.subject %>
Message:  <%= @contact_email.content %>
 

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container clearfix">
    <div class="row-fluid">
      <div class="span12">
        <div class="wrapper">
          <p>              
            <span class="bold">2013 American Financial Services Group</span><br>
              60 East 42nd Street - 40th Floor, New York, NY 10165 &bull; Tel: (212) 286-1100 &bull; Fax: (212) 286-8264 &bull; Email: <%= mail_to("contact@raisebusinessmoney.com", "contact@raisebusinessmoney.com", subject: "General") %><br>
            <span class="disclaimer">DISCLAIMER: The contents hereof do not constitute and should not be considered to be legal advice.</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_four_box_bar.html.erb
<div class= "four_box_bar">
  <div class="container"
    <div class="row-fluid">
      <div class="span12">
        <ul class="extra">
          <li class="cat_post_item-1 clearfix">
            <div></div>
            <div class="post_content">Looking for a business opportunity?</div>
          </li>
          <li class="cat_post_item-2 clearfix">
            <div></div>
            <div class="post_content">
              Want to go into a turn-key business for yourself?
            </div>
          </li>
          <li class="cat_post_item-3 clearfix">
            <div></div>
            <div class="post_content">
              Do you dream about the potential for unlimited income?              
            </div>
          </li>
          <li class="cat_post_item-4 clearfix">
            <div></div>
            <div class="post_content">
              Do you want to begin working for yourself immediately?                
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="container menu">
    <div class="row-fluid">
      <div class="span12">
        <nav class="primary">
          <ul id="topnav" class="sf-menu">
            <li><%= link_to("Home", root_path) %></li>
            <li><%= link_to("About Us", about_us_path) %></li>
            <li><%= link_to("Services", services_path) %></li>
            <li><%= link_to("Training", training_path) %></li>
            <li><%= link_to("Fees", fees_path) %></li>
            <li><%= link_to("Contact Us", contact_us_path) %></li>
          </ul>
        </nav>
      </div>
    </div>    
  </div>
</header>

app/views/layouts/_scrolling_quotes.html.erb
<div class="row-fluid scrolling_quote">
  <div class="span12">
    <div class="titlebox">       Testimonials      </div>
    <div class="quotes">"AMFSG helped me fund and open my own automotive repair business and continues to assist me whenever needed."
      <br />
      <div class="source">
        -Mark W., MLB Automotive, Inc.
      </div>
    </div>
    <div class="quotes">"AMFSG training helped me fund and start my own Insurance Brokerage business."<br />
      <div class="source">
        -Marion W., Joseph Irving & Company, Inc.
      </div>
    </div>
    <div class="quotes">"AMFSG trained and helped me start my own financial services business.  I speak to AMFSG almost every day to get their never ending support."<br />
      <div class="source">
        -Samar B., MADE Capital, Inc.
      </div>
    </div>
    <div class="quotes">"AMFSG is always available as a back-office support center for its trained group of self-employed Independent Financial Advisers."<br />
      <div class="source">
        -Gladys S., HA Capital Group
      </div>
    </div>
    <div class="quotes">"AMFSG provided me with extraordinary and continual support in running my automotive sales business."<br />
      <div class="source">
        -Joseph D, NRJ, Inc.
      </div>
    </div>
  </div>
</div>

app/views/layouts/_tagline_video_row.html.erb
<!-- Row with logo, tagline and welcome video. -->
<div class="row-fluid tag_video">
  <!-- Logo -->
  <div class="span4">
    <div class="logo">
      <%= link_to image_tag('logo3.png'), root_path, alt: "AMERICAN FINANCIAL SERVICES GROUP", title: "Unique opportunity to Raise Business Capital" %>
      <p class="description">AMERICAN FINANCIAL SERVICES GROUP</p>
      <!-- Tagline on home page-->
      <% if homepage? || test? %>
        <h2 class= "tagline">A unique opportunity<br /> to raise business </br>capital.</h2>
        <div><a href="services" class="morelink">more</a></div>
      <% end %>
    </div>
  </div>
  <!-- Only display video on home page. -->
  <% if homepage? || test? %>
    <div class="span8 video">
      <%= video_player({image: "/assets/screen_shot.png", :file => "/assets/welcome.flv", autostart: false, height: 337, :message => "You need Adobe Flash Player to see this video.", skin: "glow", controlbar: "none", stretching: "exactfit"}) %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= jquery_include_tag :google %> 
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/assets/favicon.ico' %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <%= render 'shared/flash_error_messages' %>

      <div class="primary_content_wrap">
        <%= render 'layouts/tagline_video_row' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2>Your message could not be sent because:  </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Name (required)"%>
    <%= f.text_field :name %>
  </div>
  <div class="field">
   <%= f.label :email, "Email (required)" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content, "Your Message" %>
    <%= f.text_area :content, :rows => 5 %>
  </div>
  <div class="actions"><%= f.submit "Send" %></div>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/new.html.erb
<% provide(:title, "Contact Us") %>
<div id="contact_us">
  <div class="row-fluid">
    <div class="span4">
      <div class="span12">
        <h2>Contact Us</h2>
        <div class="contact_video">
          <%= video_player({image: "/assets/contact.png", :file => "/assets/contact.flv", autostart: false, height: 337, width: 300, :message => "Get the Adobe Flash Player to see this video.", skin: "glow", controlbar: "none", stretching: "exactfit"}) %>
        </div>
        <div class='inactive_message'></div>
      </div>
      <div class="span12">
        <%= render 'form'%>
      </div>
    </div>
    <div class="span8">
      <div class="span12">
        <h2>Our Location</h2>
        <div class="map">
          <iframe src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;q=60+E+42nd+St,+New+York,+10017&amp;aq=&amp;sll=40.07304,-74.724323&amp;sspn=3.993043,10.821533&amp;ie=UTF8&amp;geocode=FfHTbQIduSyX-w&amp;split=0&amp;hq=&amp;hnear=60+E+42nd+St,+New+York,+10017&amp;t=m&amp;z=14&amp;ll=40.752113,-73.978695&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="600" height="445"></iframe>
        </div>
      </div>
      <div class="span12 contact_info">
        <h2>Contact Information</h2>
        <h6>60 East 42nd Street, 40th Floor, New York, NY 10165</h6>
        <p><b>Telephone:</b> +1 212 286 1100&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>FAX:</b> +1 212 286 8264<br /><b>E-mail:</b> <%= mail_to('info@raisebusinessmoney.com', 'info@raisebusinessmoney.com') %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_error_messages.html.erb
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>

app/views/static_pages/about_us.html.erb
<% provide(:title, "About Us") %>
<div id="about_us">
  <div class="row-fluid">
    <!-- Who we are box. -->
    <div class="span6">
      <h2>Who We Are</h2>
      <p>American Financial Services Group (&#8220;AMFSG&#8221;), with its roots stemming back to 1959, is a corporate financial advisement firm headquartered in the Lincoln Building in New York City. It is also in the business of establishing individuals to go into business for themselves, starting with a comprehensive training program.</p>
      <p>Between 1992 and 1997, AMFSG has trained more than 275 independent financial advisors in the US and Canada to advise and assist businesses in raising capital. These IFA&#8217;s are in business for themselves and do not report their income or business practices to AMFSG.</p>
      <p>Nor does AMFSG ever question them.<br />
    </div>
   <!-- About us video. -->
    <div class="span6">
      <%= video_player({image: "/assets/Screenshot-about.flv.part-1.png", :file => "/assets/about.flv", autostart: false, :message => "You need Adobe Flash Player to see this video.", skin: "glow", controlbar: "none",stretching: "exactfit"}) %>
    </div>
  </div>
  <!-- Harry Abrams box -->
  <div class="row-fluid">
    <div class="span6 about_harry">
      <h2>Harry Abrams</h2>
      <h6>Senior Partner of AMFSG</h6>
      <p>Harry Abrams has a <%= image_tag('book2.png', alt: "For the Entrepreneur:  Raising Money") %>background in law, accounting, finance and securities; he has been CEO of many public and private companies since 1959.</p>
      <p>He is currently a principal in various companies engaged in accounting, insurance, real estate, tax preparation and payroll administration.</p>
      <p>He is author of the book <span style="text-decoration: underline;">For the Entrepreneur: Raising Money</span>.</p>
    </div>
    <!-- AMFSG services provided. -->
    <div class="span6 amfsg_provides">
      <h2>AMFSG Provides:</h2>
      <ul>
        <li>Individuals with the foundation to go into business for themselves as independent financial advisors (&#8220;IFAs&#8221;).</li>
        <li>Comprehensive training.</li>
        <li>Continuous backup and ongoing support to its IFAs free of charge.</li>
        <li>Products and services of AMFSG&#8217;s subsidiaries, which may be engaged to the extent requested.</li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/fees.html.erb
<% provide(:tile, "Fees") %>
<div id="fees">
  <div class="row-fluid">
    <div class="span12">
      <h1>Fees</h1>
      <p>To be set up in your own turn-key business as an Independent Financial Advisor, including initial training given over a two-day weekend program, the one-time cost is $3,500 with the following payment options:</p>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span4">
      <b>1) Convenient installments:</b>
      <p></p>
      <ul>
        <li>$1,500 prior to training.</li>
        <li>$1,000 thirty days after completion of training.</li>
        <li>$1,000 60 days after completion of training.</li>
      </ul>
    </div>
    <div class="span4">
      <b>2) Full payment in Advanced:</b>
      <p></p>
      <ul class="payment_in_advance">
        <li>Full payment in advanced entitles you to a 10% ($350) discount.<//li>
        <li>In addition, there is a $300 discount for trainees from outside the tri-state area for travel and hotel expenses provided the full training fees are paid in advance.<//li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div id="home_page">
<%= render 'layouts/scrolling_quotes' %>
  <div class="row-fluid">
    <!-- Colored boxes -->
    <div class="span12 four_block_bar">
      <ul class="extra">
        <li class="cat_post_item-1">
          <div class="post_content">Looking for a business opportunity?</div>
        </li>
        <li class="cat_post_item-2">
          <div class="post_content">
            Want to go into a turn-key business for yourself?
          </div>
        </li>
        <li class="cat_post_item-3">
          <div class="post_content">
            Do you dream about the potential for unlimited income?              
        </div>
        </li>
        <li class="cat_post_item-4">
          <div class="post_content">
            Do you want to begin working for yourself immediately?                
          </div>
        </li>
      </ul>
    </div>
  </div>
  <!-- 2 Boxes underneath colored boxed row -->
  <div class="row-fluid double_text">
    <div class="span5 text_left">
        Become an independent, corporate financial advisor (“IFA”). As an IFA, you can operate your own business with the incredible potential for immediate and unlimited income or
      allow AMFSG to assist you raise capital for your business and/or those of your clients.
    </div>
    <!-- Box on the right is a table in order to vertically align. -->
    <div class="span7 text_right">
    <div class="text">If you've got ambition, perseverance, <br />and the entrepreneurial spirit - <br />you're in!  No prior experience required! </div>
    </div>
  </div>
  <!-- 4 colored divider -->
  <div class="banner"></div>
  <!-- New regulation row -->
  <div class="row-fluid new_regulation">
    <div class="span7 left_side">
      <h1>Join the new wave in raising capital</h1>
      <p>Let’s face it, in the current environment, it is difficult for you or any small business to borrow money, be it from a friend, family or bank. However, newly enacted legislation is designed to encourage economic growth is expanding the ability of entrepreneurs and small businesses to raise capital by:</p>
      <ul>
        <li>Permitting online advertising.</li>
        <li>Encouraging the private sector to invest.</li>
        <li>Expanding the pool of potential investors.</li>
      </ul>
    </div>
    <div class="span4 obama">
      <%= image_tag('obama.jpg', alt: "Obama", title: "Obama") %>
      <div class= "obama-text">
        President Obama signed game-changing legislation, greatly expanding the ability of startups and small businesses to raise capital.
      </div>
    </div>
  </div>
</div>

app/views/static_pages/services.html.erb
<%=provide(:title, "Services") %>
<div id="services">
  <div class="row-fluid">
    <div class="span12">
      <h1>AMFSG SERVICES</h1>
      <p>There are investors for every type of business.  In that regard, AMFSG maintains a network of over 10,000 venture capitalists, private equity investors and FINRA registered companies to assist you and/or your clients.  Selling interests (equity) in a business provides one way of raising money.</p>
      <p>Ordinarily, it can cost between $250,000 to $1,000,000 (and more) to prepare and file what is known as an initial public offering (“IPO”) with Federal and State regulatory agencies in order to sell equity.  Most small businesses cannot afford that expense (to say nothing of the time involved).  What you learn through AMFSG’s training program will enable you to raise capital for your business and/or advising your clients on how to raise capital for their businesses without incurring the staggering cost of an IPO.  You and/or your clients will also benefit from the fact that monies raised are free of taxes.</p>
     </div>
  </div>
  <div class="banner"></div>
  <div class="row-fluid">
    <div class="span6">
      <p>It is easy to find business that need money.  What business doesn't need money?
      </p>
      <h6>AMFSG will teach you to:</h6>
      <ul>
        <li>Know your role as an IFA.</li>
        <li>Be knowledgeable about how capital can be raised.</li>
        <li>Recognize the different types of companies that you and/or your clients can create.</li>
        <li>Identify sources of funding.</li>
        <li>Advertising.</li>
        <li>Navigate the laws and regulations governing raising of capital.</li>
      </ul>
    </div>
    <div class="span6">
      <p>In addition, you will always be able to receive supplemental training and AMFSG’s backup services at no additional cost.  And, you are free to engage any and all of AMFSG’s subsidiaries to provide various products and services for you or your clients.</p>
      <h6>Those services include:</h6>
      <ul>
        <li>Accounting</li>
        <li>Insurance</li>
        <li>Real Estate</li>
        <li>Tax Preparation</li>
        <li>Payroll Administration</li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/test.html.erb
<div id="home_page">
  <div class="row-fluid scrolling_quote">
    <div class="span12">
      <div class="titlebox">       Testimonials      </div>
      <div class="quotes">"AMFSG helped me fund and open my own automotive repair business and continues to assist me whenever needed."
        <br />
        <div class="source">
          -Mark W., MLB Automotive, Inc.
        </div>
      </div>
      <div class="quotes">"AMFSG training helped me fund and start my own Insurance Brokerage business."<br />
        <div class="source">
          -Marion W., Joseph Irving & Company, Inc.
        </div>
      </div>
      <div class="quotes">"AMFSG trained and helped me start my own financial services business.  I speak to AMFSG almost every day to get their never ending support."<br />
        <div class="source">
          -Samar B., MADE Capital, Inc.
        </div>
      </div>
      <div class="quotes">"AMFSG is always available as a back-office support center for its trained group of self-employed Independent Financial Advisers."<br />
        <div class="source">
          -Gladys S., HA Capital Group
        </div>
      </div>
      <div class="quotes">"AMFSG provided me with extraordinary and continual support in running my automotive sales business."<br />
        <div class="source">
          -Joseph D, NRJ, Inc.
        </div>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <!-- Colored boxes -->
    <div class="span12 four_block_bar">
      <ul class="extra">
        <li class="cat_post_item-1">
          <div class="post_content">Looking for a business opportunity?</div>
        </li>
        <li class="cat_post_item-2">
          <div class="post_content">
            Want to go into a turn-key business for yourself?
          </div>
        </li>
        <li class="cat_post_item-3">
          <div class="post_content">
            Do you dream about the potential for unlimited income?              
        </div>
        </li>
        <li class="cat_post_item-4">
          <div class="post_content">
            Do you want to begin working for yourself immediately?                
          </div>
        </li>
      </ul>
    </div>
  </div>
  <!-- 2 Boxes underneath colored boxed row -->
  <div class="row-fluid double_text">
    <div class="span5 text_left">
        Become an independent, corporate financial advisor (“IFA”). As an IFA, you can operate your own business with the incredible potential for immediate and unlimited income or
      allow AMFSG to assist you raise capital for your business and/or those of your clients.
    </div>
    <!-- Box on the right is a table in order to vertically align. -->
    <div class="span7 text_right">
    <div class="text">If you've got ambition, perseverance, <br />and the entrepreneurial spirit - <br />you're in!  No prior experience required! </div>
    </div>
  </div>
  <!-- 4 colored divider -->
  <div class="banner"></div>
  <!-- New regulation row -->
  <div class="row-fluid new_regulation">
    <div class="span7 left_side">
      <h1>Join the new wave in raising capital</h1>
      <p>Let’s face it, in the current environment, it is difficult for you or any small business to borrow money, be it from a friend, family or bank. However, newly enacted legislation is designed to encourage economic growth is expanding the ability of entrepreneurs and small businesses to raise capital by:</p>
      <ul>
        <li>Permitting online advertising.</li>
        <li>Encouraging the private sector to invest.</li>
        <li>Expanding the pool of potential investors.</li>
      </ul>
    </div>
    <div class="span4 obama">
      <%= image_tag('obama.jpg', alt: "Obama", title: "Obama") %>
      <div class= "obama-text">
        President Obama signed game-changing legislation, greatly expanding the ability of startups and small businesses to raise capital.
      </div>
    </div>
  </div>
</div>

app/views/static_pages/training.html.erb
<% provide(:title, 'Training') %>
<div id="training">
  <div class="row-fluid">
    <div class="span8">
      <!-- AMFSG training section. -->
      <h2>AMFSG Training</h2>
      <p>With AMFSG&#8217;s training, you will learn how to raise capital for your own business or help others raise money for their businesses.  One unique aspect of becoming an independent financial advisor (IFA) is that the field is filled with opportunity.</p>
      <p>In addition, you will have the option to receive supplemental training and engage AMFSG&#8217;s subsidiaries to provide various products and services for you or your clients. AMFSG offers a unique opportunity for its trained IFAs to provide companies and individuals with capital and financial services, while generating substantial income and profits for themselves.</p>
      <p></p>
      <h6>AMFSG&#8217;s training is geared to fit your individual requirements.</h6>
      <ul>
        <li>You can be part of group weekend training programs conducted in New York City or you can arrange for private training in or outside New York.</li>
        <li>All materials and documents supplied.</li>
        <li>Booster training whenever needed.</li>
      </ul>
      <p>Contact AMFSG for details and scheduling.</p>
    </div>
    <!-- AMFSG training video. -->
    <div class="span4 training_video">
      <%= video_player({image: "/assets/training.png", :file => "/assets/training.flv", autostart: false, :message => "You need Adobe Flash Player to see this video.", skin: "glow", controlbar: "none",stretching: "exactfit"}) %>
    </div>
  </div>
  <div class="banner" style="margin: 25px 0 30px 0;">
    <p>Your potential gain? The Sky&#8217;s the limit!</p>
  </div>
  <div class="row-fluid">
    <!-- Advantages -->
    <div class="span6">
      <h2>The advantages of becoming an IFA are many.</h2>
      <ul>
      <li>No experience is needed.</li>
        <li>Any type of business can be your client – every business needs money.</li>
        <li>There are investors for every type of business.</li>
        <li>You will be your own boss.</li>
      </ul>
    </div>
    <div class="span6">
      <!-- Teaching -->
      <h2>AMFSG will teach you to:</h2>
      <ul>
        <li>Know your role as an IFA.</li>
        <li>Be knowledgeable about how to raise capital.</li>
        <li>Recognize the best types of companies and organizations for you or your clients to create. </li>
        <li>Identify sources of funding.</li>
        <li>Advertise on the internet to raise money.</li>
        <li>Navigate the laws and regulations governing raising of capital.</li>
      </ul>
    </div>
  </div>
</div>